# Generated by Django 3.2 on 2024-03-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yamdbuser',
            name='confirmation_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
