# Generated by Django 3.2 on 2024-03-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_yamdbuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamdbuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Код подтверждения'),
        ),
        migrations.AlterField(
            model_name='yamdbuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Адрес электронной почты.'),
        ),
        migrations.AlterField(
            model_name='yamdbuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Пароль.'),
        ),
    ]
