# Generated by Django 3.2 on 2024-03-20 14:32

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20240320_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(max_length=4, validators=[reviews.validators.validate_year], verbose_name='Год выпуска'),
        ),
    ]
